# https://docs.github.com/cn/actions/automating-builds-and-tests/building-and-testing-python

name: Update dailyNews

on:
  watch:
    types: [started]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "*.py"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Push articles
        env:
          FEISHU_KEY: ${{ secrets.FEISHU_KEY }}
          WECOM_KEY: ${{ secrets.WECOM_KEY }}
          DINGTALK_KEY: ${{ secrets.DINGTALK_KEY }}
          TELEGRAM_KEY: ${{ secrets.TELEGRAM_KEY }}
          MAIL_KEY: ${{ secrets.MAIL_KEY }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
        run: python3 yarb.py

      - name: Commit & Push
        run: |
          git status
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git add rss/rss.db3
          git commit -m "每日资讯（`date +'%Y-%m-%d'`）"
          git push origin main
          cp archive archive1
          
          git checkout archive
          mv -f archive1/* archive/
          git add archive
          git commit -m "每日存档（`date +'%Y-%m-%d'`）"
          git push origin archive

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     # github_token: ${{ secrets.MY_GITHUB_TOKEN }}
      #     branch: main

      - name: Delete Workflow Runs
        uses: anaer/delete-workflow-runs@main
        with:
          retain_days: 3
          keep_minimum_runs: 5
